---
- hosts: all
  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      # This allows the playbook to "succeed" even if one mirror is 404ing
      ignore_errors: yes

    - name: Clean up old packages
      apt:
        autoremove: yes
        purge: yes
